name: preflight-checks
on:
  push:
    tags:
      - "v*"
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  plugin-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd ./plugin
      - run: npm install
      - run: npm run test

  publish-plugin:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [plugin-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd ./plugin
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: ./plugin/package.json

  publish-generator:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd ./yeoman-generator
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: ./yeoman-generator/package.json
