name: preflight-checks
on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  plugin-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install deps
        run: npm install
        working-directory: ./plugin
      - name: run tests
        run: npm run test
        working-directory: ./plugin

  publish-plugin:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [plugin-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install deps
        run: npm install
        working-directory: ./plugin
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: ./plugin/package.json

  publish-generator:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [plugin-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install deps
        run: npm install
        working-directory: ./yeoman-generator
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: ./yeoman-generator/package.json
